from pathlib import Path
from textwrap import wrap

import yaml


def _split_skill_frontmatter(contents: str) -> tuple[dict[str, object], str]:
    if not contents.startswith("---\n"):
        return {}, contents

    _, frontmatter, body = contents.split("---\n", 2)
    metadata = yaml.safe_load(frontmatter) or {}
    if not isinstance(metadata, dict):
        return {}, body
    return metadata, body


def _read_skill_body_summary(skill_md: Path) -> str:
    _, body = _split_skill_frontmatter(skill_md.read_text(encoding="utf-8"))
    lines = body.splitlines()
    paragraphs: list[list[str]] = []
    current: list[str] = []

    for line in lines:
        stripped = line.strip()
        if not stripped:
            if current:
                paragraphs.append(current)
                current = []
            continue
        if stripped.startswith("#"):
            continue
        current.append(stripped)

    if current:
        paragraphs.append(current)

    return " ".join(paragraphs[0]) if paragraphs else ""


def _read_agent_interface(skill_dir: Path) -> dict[str, object]:
    agent_metadata_path = skill_dir / "agents" / "openai.yaml"
    if not agent_metadata_path.exists():
        return {}

    agent_metadata = yaml.safe_load(agent_metadata_path.read_text(encoding="utf-8"))
    if not isinstance(agent_metadata, dict):
        return {}

    interface = agent_metadata.get("interface")
    return interface if isinstance(interface, dict) else {}


def _read_skill_display_name(
    skill_dir: Path, metadata: dict[str, object], interface: dict[str, object]
) -> str:
    if interface.get("display_name"):
        return str(interface["display_name"])

    name = str(metadata.get("name") or skill_dir.name)
    return name.replace("-", " ").title()


def _read_skill_summary(skill_md: Path, interface: dict[str, object]) -> str:
    if interface.get("short_description"):
        return str(interface["short_description"])
    return _read_skill_body_summary(skill_md)


def _extend_wrapped_paragraph(
    lines: list[str], text: str, *, width: int = 88, prefix: str = ""
) -> None:
    lines.extend([prefix + l for l in wrap(text, width=width)] or [""])


def write_generated_agent_skills_docs(
    *,
    project_root: Path,
    docs_root: Path,
    source_repository: str,
    source_branch: str,
) -> None:
    skills_dir = project_root / "skills"
    output_path = docs_root / "deployments" / "agent-skills.md"

    lines = [
        "<!-- Auto-generated by docs/agent_skills_docs.py from skills/. Do not edit by hand. -->",
        "",
        "# Agent Skills",
        "",
    ]
    _extend_wrapped_paragraph(
        lines,
        "Nomad publishes agent skills as folders under {repo_file}`skills/`. "
        "Each skill is a portable bundle of instructions and references that an "
        "AI coding agent can load when helping you build or validate a Nomad "
        "deployment.",
    )
    lines.append("")

    skill_dirs = sorted(
        path for path in skills_dir.iterdir() if (path / "SKILL.md").exists()
    )
    if not skill_dirs:
        lines.extend(
            [
                "No agent skills are currently published in this repository.",
                "",
            ]
        )

    for skill_dir in skill_dirs:
        skill_md = skill_dir / "SKILL.md"
        metadata, _ = _split_skill_frontmatter(skill_md.read_text(encoding="utf-8"))
        interface = _read_agent_interface(skill_dir)
        display_name = _read_skill_display_name(skill_dir, metadata, interface)
        summary = _read_skill_summary(skill_md, interface)
        skill_url = f"{source_repository}/tree/{source_branch}/skills/{skill_dir.name}"
        skill_dir = f"skills/{skill_dir.name}"

        lines.extend([f"## {{repo_file}}`{display_name}<{skill_dir}>`", ""])
        _extend_wrapped_paragraph(lines, summary)
        lines.extend(
            [
                "",
                "Ask your agent to download and install the skill into its skills directory:",
                "",
                "```text",
                f"Download the skill from {skill_url}, ",
                "resolve any symlinked references, and set it up in my skills directory.",
                "Then show me how to use the skill.",
                "```",
                "",
            ]
        )

        lines.append("")

    lines.extend(["", "## Installing Skills", ""])
    _extend_wrapped_paragraph(
        lines,
        "Different agents store skills in different places and may have their "
        "own installer commands. Let the agent choose the correct "
        "installation path and workflow for the environment you are using. "
        "If an installer copies only the skill folder, it should materialize "
        "or replace symlinked references that point elsewhere in the Nomad "
        "repository.",
    )
    output_path.write_text("\n".join(lines), encoding="utf-8")
